### PR TITLE
GH-71 Provision 4.0.10 issue

### LINKED ISSUE #71: Provision 4.0.10 issue
```
git pull
vagrant up iscsi adm mds1 mds2 oss1 oss2 c1
vagrant provision adm --provision-with install-iml-4.0.10
```
error
```
$ vagrant provision adm --provision-with install-iml-4.0.10
==> adm: [vagrant-hostsupdater] Checking for host entries
==> adm: [vagrant-hostsupdater]   found entry for: 10.73.10.10 adm.local
==> adm: Running provisioner: install-iml-4.0.10 (shell)...
    adm: Running: /var/folders/8p/1np41wmd56qg89shnvwskhd12r6prh/T/vagrant-shell20190924-88344-13y2429.sh
    adm: Loaded plugins: fastestmirror
    adm: Repository extras is listed more than once in the configuration
    adm: Repository epel is listed more than once in the configuration
    adm: adding repo from: https://raw.githubusercontent.com/whamcloud/integrated-manager-for-lustre/v4.0.10.2/chroma-bundles/chroma_support.repo
    adm: grabbing file https://raw.githubusercontent.com/whamcloud/integrated-manager-for-lustre/v4.0.10.2/chroma-bundles/chroma_support.repo to /etc/yum.repos.d/chroma_support.repo
    adm: repo saved to /etc/yum.repos.d/chroma_support.repo
    adm: Loaded plugins: copr, fastestmirror
    adm: Repository extras is listed more than once in the configuration
    adm: Repository epel is listed more than once in the configuration
    adm: Loading mirror speeds from cached hostfile
    adm:  * base: centos.slaskdatacenter.com
    adm:  * epel: mirror.logol.ru
    adm:  * extras: centos1.hti.pl
    adm:  * updates: centos.slaskdatacenter.com
    adm: No package python2-iml-manager available.
    adm: Error: Nothing to do
    adm: /tmp/vagrant-shell: line 5: chroma-config: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

May be related to missing some rpm mirror during install

### PR DESCRIPTION
**Pull request by johnsonw**
Fixes #71.

Fix provisioning script for 4.0.10.

Signed-off-by: Will Johnson <wjohnson@whamcloud.com>

### CODE REVIEW

File: scripts/install_iml_tar.sh [hunk 1]
```diff
@@ -0,0 +1,5 @@
+cd /tmp
+curl -L $1 | tar zx
+cd /tmp/iml-4*
```
Comment (johnsonw) [inline scripts/install_iml_tar.sh]: This needs to be updated.

**Comment by bm13kk** [comment]
issues:
1) get input from chroma - already in progress
2) output is killing, at least 400 lines of:
```
/   adm: 
\   adm: 
|   adm: 
/   adm: 
-   adm: 
\   adm: 
|   adm: 
/   adm: 
-   adm: 
\   adm: 
|   adm: 
/   adm: 
-   adm: 
\   adm: 
|   adm: 
/   adm: 
-   adm: 
\   adm: 
|   adm: 
/   adm: 
-   adm: 
\   adm: 
```

**Comment by johnsonw** [comment]
@bm13kk the problem was that the script was looking for input from stdin and it was just sitting forever waiting for input. I tried a few different approaches but piping content in doesn't solve the problem. The next closest thing was to use `yes` but this will continuously send then same single value and will not account for multiple prompts in the script. It seemed the only option I had left was to use `expect`, which has been consistently reliable.

**Comment by johnsonw** [comment]
install-iml-4 10 2-provision-script

**Comment by bm13kk** [comment]
deploy successfully finished.

web partially working - I see infinite loading circle.

File: scripts/install_iml_tar.sh [hunk 2]
```diff
@@ -0,0 +1,31 @@
+mkdir -p /tmp/iml-install
+cd /tmp/iml-install
+curl -L $1 | tar zx --strip 1
+yum install -y expect
```
Comment (jgrund) [inline scripts/install_iml_tar.sh]: Instead of using an inline expect script, we can pull the existing expect script from the relevant tag, ex:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/v4.0.10.2/chroma-manager/tests/utils/install.exp

Comment (johnsonw) [reply scripts/install_iml_tar.sh]: I've updated to use this existing expect script and tested locally. Install worked without any issues.

**Comment by johnsonw** [comment]
image

**Comment by bm13kk** [comment]
commits 4 and 5 working for me

but i think we should fix output in future

**Comment by bm13kk** [comment]
check this comment https://github.com/whamcloud/integrated-manager-for-lustre/issues/1217#issuecomment-535137946
